# Site settings
author: Dominick
title: The Little Professor
header-img: img/home-bg.png
email: dcascone84@gmail.com
copyright_name: Dominick
description: > # this means to ignore newlines until "baseurl:"
  A dream doesn't become reality through magic; it takes sweat, determin
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cdominick091984

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
